import { Channel, ChannelCategory } from './types';

export const ADMIN_PASSWORD = "admin!123!";

export const SYSTEM_CHANNELS: Channel[] = [
  {
    id: 'stiletv',
    name: 'StileTV',
    category: ChannelCategory.LOCAL,
    description: 'Diretta streaming di StileTV. Informazione e cultura dalla Campania. La prima emittente di Paestum, Capaccio e del Cilento.',
    logoUrl: 'https://yt3.googleusercontent.com/-gTs9ve1u54V9JjOFL0BsftU47b1GBrtaqNpZ62tZgOoSw6J33CeYwKEWd2t33yzW8924f-MIA=s160-c-k-c0x00ffffff-no-rj',
    streamType: 'direct_url',
    streamUrl: 'https://proxy.media.convergenze.it/stiletv/streams/oQOFd7JglHjO1631525551097.m3u8',
    isLive: true,
    websiteUrl: 'https://www.stiletv.it',
    rssUrl: 'https://www.stiletv.it/rss-totale.xml', 
    youtubeChannelId: 'UCTiXIswTEO-wBIEgBTrnH3w',
    rating: 5,
    viewCount: 0,
    isUserAdded: false,
    order: 1
  },
  {
    id: 'settv',
    name: 'SET',
    category: ChannelCategory.LOCAL,
    description: 'SET TV - Scelza Edizioni Televisive. Emittente televisiva di Vallo della Lucania.',
    logoUrl: 'https://yt3.googleusercontent.com/QsPqqdEviqLKBdVluuD4qDWR94naYptfPmMWvQ02ENrL2ItWzx7UGZQcisagk1T7JVlDvP8I7A=s160-c-k-c0x00ffffff-no-rj',
    streamType: 'direct_url',
    streamUrl: 'https://stream1.aswifi.it/settv/live/index.m3u8',
    isLive: true,
    websiteUrl: 'https://www.settv.it',
    rssUrl: '',
    youtubeChannelId: '',
    rating: 0,
    viewCount: 0,
    isUserAdded: false,
    order: 2
  },
  {
    id: 'zonarcs',
    name: 'Zona RCS75',
    category: ChannelCategory.LOCAL,
    description: 'RCS75 - Radio Castelluccio. La Radio-TV del Sud. Musica, informazione e intrattenimento.',
    logoUrl: 'https://www.zonarcs.tv/wp-content/uploads/2025/04/zona-rcs-tv-111-262x149.jpg',
    streamType: 'direct_url',
    streamUrl: 'https://play.xdevel.com/13592?fromPW=MQ==',
    isLive: true,
    websiteUrl: 'https://www.zonarcs.tv',
    rssUrl: 'https://www.zonarcs.tv/feed/',
    youtubeChannelId: '',
    rating: 0,
    viewCount: 0,
    isUserAdded: false,
    order: 3
  },
  {
    id: 'televomero',
    name: 'Televomero',
    category: ChannelCategory.LOCAL,
    description: 'Televomero, la televisione al servizio dei cittadini di Napoli. Cronaca, sport, cultura.',
    logoUrl: 'https://www.televomero.it/wp-content/uploads/2023/10/televomeroLogoNewX2.png',
    streamType: 'direct_url',
    streamUrl: 'https://play.xdevel.com/65',
    isLive: true,
    websiteUrl: 'https://www.televomero.it',
    rssUrl: 'https://www.televomero.it/feed/',
    youtubeChannelId: '',
    rating: 0,
    viewCount: 0,
    isUserAdded: false,
    order: 4
  },
  {
    id: 'infocilento',
    name: 'InfoCilento',
    category: ChannelCategory.LOCAL,
    description: 'InfoCilento - Il portale di informazione del Cilento, Vallo di Diano e Alburni.',
    logoUrl: 'https://www.infocilento.it/wp-content/uploads/2024/03/logo-X-60.png',
    streamType: 'direct_url',
    streamUrl: 'https://nrvideo1.newradio.it:8080/VideoPlayer/pskfvahhcs?autoplay=1',
    isLive: true,
    websiteUrl: 'https://www.infocilento.it',
    rssUrl: 'https://www.infocilento.it/feed/',
    youtubeChannelId: '',
    rating: 0,
    viewCount: 0,
    isUserAdded: false,
    order: 5
  },
  {
    id: 'telea',
    name: 'Tele A',
    category: ChannelCategory.LOCAL,
    description: 'Tele A, storica emittente televisiva commerciale con sede a Napoli, visibile in tutto il Sud Italia.',
    logoUrl: 'https://www.teleatv.it/Loghi/TeleA.png',
    streamType: 'direct_url',
    streamUrl: 'https://palpro.it/telea/',
    isLive: true,
    websiteUrl: 'https://www.teleatv.it',
    rssUrl: '',
    youtubeChannelId: '',
    rating: 0,
    viewCount: 0,
    isUserAdded: false,
    order: 6
  }
];